### ISSUE TITLE
Issues to solve before Glances 3.4.0 release

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2393]
I just push a release candidate (RC1) on the develop branch.

Unfortunately, there are some issues to solve before the release:

- [x] CPU consumption is higher (~30%) than Glances 3.3.1 - #2390
- [x] Error while generating the documentation (ModuleNotFoundError: No module named 'glances') -  #2391
- [ ]  Docker plugins do not work as expected inside Glances docker images #2392  => **Workaround pushed on develop**
- [x] WebUI failed to build with the latest VueJS (3.3.2). Downgraded to 3.2.47 on the RC1 - #2389

**Comment by nicolargo** [comment]
All errors solved.

Let the issue #2392 (tag for next version) because it is a workaround waiting for the upstream patch on Podman-Py .
