### ISSUE TITLE
On the road of Glances version 4.0.0

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2400]
Glances 3.4.x will be the latest versions (only hotfix will be merged) with a full support of Python 2.7 and Python 3 < 3.8.

The new develop branch (future version 4) will only support Python 3.8 or higher.

- [ ]  release Glances 3.4.0 (from the develop branch)
- [ ] create a new support/glancesv3 branch from the develop branch (hotfix for Glances 3.x)
- [ ] merge glancesv4 branch into develop
- [ ]  remove glances v4 branch

**Comment by nicolargo** [comment]
**Roadmap for Glances version 4.0.0**

Code refactoring (better to be done before others issues):

- https://github.com/nicolargo/glances/issues/2409
- https://github.com/nicolargo/glances/issues/2404
- https://github.com/nicolargo/glances/issues/2198
- https://github.com/nicolargo/glances/issues/2183
- https://github.com/nicolargo/glances/issues/1930
- https://github.com/nicolargo/glances/issues/1735

WebUI improvement/refactoring:
- https://github.com/nicolargo/glances/issues/2181
- https://github.com/nicolargo/glances/issues/2114
- https://github.com/nicolargo/glances/issues/2048
- https://github.com/nicolargo/glances/issues/1515

Improve GPU plugin:

- https://github.com/nicolargo/glances/issues/994
- https://github.com/nicolargo/glances/issues/993
- https://github.com/nicolargo/glances/issues/1048

Others Improvements:

- https://github.com/nicolargo/glances/issues/794
- https://github.com/nicolargo/glances/issues/2394
- https://github.com/nicolargo/glances/issues/1995
- https://github.com/nicolargo/glances/issues/1882
- https://github.com/nicolargo/glances/issues/1881
- https://github.com/nicolargo/glances/issues/1534
- https://github.com/nicolargo/glances/issues/1527
- https://github.com/nicolargo/glances/issues/1524
- https://github.com/nicolargo/glances/issues/1432
- https://github.com/nicolargo/glances/issues/1289
- https://github.com/nicolargo/glances/issues/995

News features:

- https://github.com/nicolargo/glances/issues/2252
- https://github.com/nicolargo/glances/issues/1989
- https://github.com/nicolargo/glances/issues/1626

Bugs to be corrected:

- https://github.com/nicolargo/glances/issues/2392
- https://github.com/nicolargo/glances/issues/2214
- https://github.com/nicolargo/glances/issues/2213
- https://github.com/nicolargo/glances/issues/1377
