### ISSUE TITLE
Reduce complexity of `Makefile`

### ISSUE THREAD

**Issue by ariel-anieli** [nicolargo/glances#2906]
Hello,

This issue is for tracking the ongoing effort on `Makefile`. Might help for #2583:

- [x] Factorize with variables (#2907)
- [x] When targets have same templates, for instance `test-*`, use pattern rules:

1. #2910 
2. #2913
3. #2917

- [x] ~~put `tests-*` in a test folder~~ (TODO: this breaks `glances` imports in `unitttest-*.py`)
- [x] ~~evaluate if virtual paths would be helpful in the rules using docker files and test scripts~~ (TODO: first of all, `unitttest-*.py` import breaks need to be solved)
- [x] ~~Remove dependencies to external files; i.e., `*-requirements.txt`~~ (TODO: should be part a task in itself, could be extended to the Docker requirements)
- [x] ~~use patterns as in #2917. Here is the pattern: `VIRTUAL_ENV/python FLAGS TARGET`~~ (decrease legibility)

- [x] Fix bug on `make test-restful` (unrelated to `Makefile`, opened #2918)
```shell
# make test-restful 1>/dev/null
INFO:     Started server process [812050]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:61234 (Press CTRL+C to quit)
...F.............INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [812050]
.
======================================================================
FAIL: test_003_plugins (__main__.TestGlances.test_003_plugins)
Plugins.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ariel/src/python/glances/unittest-restful.py", line 120, in test_003_plugins
    self.assertIsInstance(req.json(), list)
AssertionError: {} is not an instance of <class 'list'>

----------------------------------------------------------------------
Ran 18 tests in 6.277s

FAILED (failures=1)
make: *** [Makefile:90: test-restful] Error 1
```
